### ISSUE TITLE
JSON not working as expected

### ISSUE THREAD

**Issue by StephanSchmidt** [adolfo/optional-go#4]
JSON generation is not working as intended for me:

```
type data struct {
	Bogus     optional.Value[string] `json:"bogus"`
	Bigus     optional.Value[string] `json:"bigus"`
}

data := data{
			Bogus:     optional.Of("YES!"),
}
```

and `json.Marshal(d)`

generates

`{"bogus":{},"bigus":{}}
`

Do I need to import something additional?

**Comment by adolfo** [comment]
@StephanSchmidt thanks for the report! Please take a look at release v0.1.1. It addresses this issue.

**Comment by StephanSchmidt** [comment]
Hello @adolfo great! 

I've tried the 0.1.1 release and it works somehow, but not as expected.

I now get `{bogus":"YES!","bigus":null}` but would like to have `{bogus":"YES!"}` with 

```
type data struct {
	Bogus     optional.Value[string] `json:"bogus,omitempty"`
	Bigus     optional.Value[string] `json:"bigus,omitempty"`
}
```
and
```
data := data{
  Bogus:     optional.Of("YES!"),
  Bigus:     optional.OfNil[string](),
}
```

How would I get rid of the `null` ?

**Comment by adolfo** [comment]
Ah I see. The default behavior is to return `null` if the optional is nil. Let me take a look and see what we can do. It should respect the `omitempty` json tag.

**Comment by StephanSchmidt** [comment]
Is there another way to set the optional to empty beside `OfNil`?

I haven't tried unmarshal yet, I would expect `{bogus":"YES!"}` to unmarshal `Bigus     optional.Value[string]` with the empty value, would that work?

For context I'm storing the JSON into Postgres with pgx.

**Comment by adolfo** [comment]
If you omit the member it will default to `nil`. e.g.:
```
type data struct {
	Bogus     optional.Value[string] `json:"bogus,omitempty"`
	Bigus     optional.Value[string] `json:"bigus,omitempty"`
}

data := data {
  Bogus:     optional.Of("YES!"),
}

// JSON
{bogus":"YES!","bigus":null}
```

**Comment by StephanSchmidt** [comment]
Is the nil wrapped in Value? Can I call `data.Bigus.isNil()`? Or will this panic?

**Comment by adolfo** [comment]
It will not panic if you call `isNil()` (unless `data.Bigus` is a nil pointer which it shouldn't be.)

**Comment by StephanSchmidt** [comment]
Excellent! Waiting for the next release with the `omitempty` fix :-)
